export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      grammar: {
        Row: {
          id: string;
          source_key: string;
          title: string;
          slug: string;
          jlpt_level: "N1" | "N2" | "N3" | "N4" | "N5";
          source_route: "蓝宝书" | "TRY" | "一册合格" | "综合";
          grammar_type: string;
          tags: string[];
          meaning_cn: string;
          meaning_zh: string | null;
          meaning_en: string;
          structure: string;
          explanation: string;
          explanation_zh: string | null;
          explanation_en: string | null;
          usage_note: string;
          usage_note_zh: string | null;
          usage_note_en: string | null;
          example_jp: string;
          example_cn: string;
          example_zh: string | null;
          example_en: string | null;
          furigana: string | null;
          similar_grammar: Json;
          common_mistake: string;
          common_mistake_zh: string | null;
          common_mistake_en: string | null;
          memory_tip: string;
          memory_tip_zh: string | null;
          memory_tip_en: string | null;
          quiz_question: string;
          quiz_choices: Json;
          quiz_answer: string;
          quiz_explanation: string;
          is_system: boolean;
          content_version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source_key?: string;
          title: string;
          slug: string;
          jlpt_level: "N1" | "N2" | "N3" | "N4" | "N5";
          source_route: "蓝宝书" | "TRY" | "一册合格" | "综合";
          grammar_type: string;
          tags?: string[];
          meaning_cn: string;
          meaning_zh?: string | null;
          meaning_en?: string;
          structure?: string;
          explanation?: string;
          explanation_zh?: string | null;
          explanation_en?: string | null;
          usage_note?: string;
          usage_note_zh?: string | null;
          usage_note_en?: string | null;
          example_jp?: string;
          example_cn?: string;
          example_zh?: string | null;
          example_en?: string | null;
          furigana?: string | null;
          similar_grammar?: Json;
          common_mistake?: string;
          common_mistake_zh?: string | null;
          common_mistake_en?: string | null;
          memory_tip?: string;
          memory_tip_zh?: string | null;
          memory_tip_en?: string | null;
          quiz_question?: string;
          quiz_choices?: Json;
          quiz_answer?: string;
          quiz_explanation?: string;
          is_system?: boolean;
          content_version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          source_key?: string;
          title?: string;
          slug?: string;
          jlpt_level?: "N1" | "N2" | "N3" | "N4" | "N5";
          source_route?: "蓝宝书" | "TRY" | "一册合格" | "综合";
          grammar_type?: string;
          tags?: string[];
          meaning_cn?: string;
          meaning_zh?: string | null;
          meaning_en?: string;
          structure?: string;
          explanation?: string;
          explanation_zh?: string | null;
          explanation_en?: string | null;
          usage_note?: string;
          usage_note_zh?: string | null;
          usage_note_en?: string | null;
          example_jp?: string;
          example_cn?: string;
          example_zh?: string | null;
          example_en?: string | null;
          furigana?: string | null;
          similar_grammar?: Json;
          common_mistake?: string;
          common_mistake_zh?: string | null;
          common_mistake_en?: string | null;
          memory_tip?: string;
          memory_tip_zh?: string | null;
          memory_tip_en?: string | null;
          quiz_question?: string;
          quiz_choices?: Json;
          quiz_answer?: string;
          quiz_explanation?: string;
          is_system?: boolean;
          content_version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_grammar_overrides: {
        Row: {
          id: string;
          user_id: string;
          grammar_source_key: string;
          hidden: boolean;
          title: string | null;
          slug: string | null;
          jlpt_level: "N1" | "N2" | "N3" | "N4" | "N5" | null;
          source_route: "蓝宝书" | "TRY" | "一册合格" | "综合" | null;
          grammar_type: string | null;
          tags: string[] | null;
          meaning_cn: string | null;
          meaning_zh: string | null;
          meaning_en: string | null;
          structure: string | null;
          explanation: string | null;
          explanation_zh: string | null;
          explanation_en: string | null;
          usage_note: string | null;
          usage_note_zh: string | null;
          usage_note_en: string | null;
          example_jp: string | null;
          example_cn: string | null;
          example_zh: string | null;
          example_en: string | null;
          furigana: string | null;
          similar_grammar: Json | null;
          common_mistake: string | null;
          common_mistake_zh: string | null;
          common_mistake_en: string | null;
          memory_tip: string | null;
          memory_tip_zh: string | null;
          memory_tip_en: string | null;
          quiz_question: string | null;
          quiz_choices: Json | null;
          quiz_answer: string | null;
          quiz_explanation: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          grammar_source_key: string;
          hidden?: boolean;
          title?: string | null;
          slug?: string | null;
          jlpt_level?: "N1" | "N2" | "N3" | "N4" | "N5" | null;
          source_route?: "蓝宝书" | "TRY" | "一册合格" | "综合" | null;
          grammar_type?: string | null;
          tags?: string[] | null;
          meaning_cn?: string | null;
          meaning_zh?: string | null;
          meaning_en?: string | null;
          structure?: string | null;
          explanation?: string | null;
          explanation_zh?: string | null;
          explanation_en?: string | null;
          usage_note?: string | null;
          usage_note_zh?: string | null;
          usage_note_en?: string | null;
          example_jp?: string | null;
          example_cn?: string | null;
          example_zh?: string | null;
          example_en?: string | null;
          furigana?: string | null;
          similar_grammar?: Json | null;
          common_mistake?: string | null;
          common_mistake_zh?: string | null;
          common_mistake_en?: string | null;
          memory_tip?: string | null;
          memory_tip_zh?: string | null;
          memory_tip_en?: string | null;
          quiz_question?: string | null;
          quiz_choices?: Json | null;
          quiz_answer?: string | null;
          quiz_explanation?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          grammar_source_key?: string;
          hidden?: boolean;
          title?: string | null;
          slug?: string | null;
          jlpt_level?: "N1" | "N2" | "N3" | "N4" | "N5" | null;
          source_route?: "蓝宝书" | "TRY" | "一册合格" | "综合" | null;
          grammar_type?: string | null;
          tags?: string[] | null;
          meaning_cn?: string | null;
          meaning_zh?: string | null;
          meaning_en?: string | null;
          structure?: string | null;
          explanation?: string | null;
          explanation_zh?: string | null;
          explanation_en?: string | null;
          usage_note?: string | null;
          usage_note_zh?: string | null;
          usage_note_en?: string | null;
          example_jp?: string | null;
          example_cn?: string | null;
          example_zh?: string | null;
          example_en?: string | null;
          furigana?: string | null;
          similar_grammar?: Json | null;
          common_mistake?: string | null;
          common_mistake_zh?: string | null;
          common_mistake_en?: string | null;
          memory_tip?: string | null;
          memory_tip_zh?: string | null;
          memory_tip_en?: string | null;
          quiz_question?: string | null;
          quiz_choices?: Json | null;
          quiz_answer?: string | null;
          quiz_explanation?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_grammar_items: {
        Row: Database["public"]["Tables"]["grammar"]["Row"] & {
          user_id: string;
          deleted_at: string | null;
        };
        Insert: Database["public"]["Tables"]["grammar"]["Insert"] & {
          user_id: string;
          deleted_at?: string | null;
        };
        Update: Database["public"]["Tables"]["grammar"]["Update"] & {
          user_id?: string;
          deleted_at?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          avatar_url: string | null;
          streak_days: number;
          created_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          streak_days?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          streak_days?: number;
          created_at?: string;
        };
      };
      user_grammar_progress: {
        Row: {
          id: string;
          user_id: string;
          grammar_id: string | null;
          grammar_key: string;
          study_status: "未学习" | "学习中" | "已掌握";
          is_favorite: boolean;
          review_count: number;
          mastery_level: number;
          interval: number;
          repetition: number;
          ease_factor: number;
          next_review_at: string | null;
          last_reviewed_at: string | null;
          last_rating: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          grammar_id?: string | null;
          grammar_key: string;
          study_status?: "未学习" | "学习中" | "已掌握";
          is_favorite?: boolean;
          review_count?: number;
          mastery_level?: number;
          interval?: number;
          repetition?: number;
          ease_factor?: number;
          next_review_at?: string | null;
          last_reviewed_at?: string | null;
          last_rating?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          grammar_id?: string | null;
          grammar_key?: string;
          study_status?: "未学习" | "学习中" | "已掌握";
          is_favorite?: boolean;
          review_count?: number;
          mastery_level?: number;
          interval?: number;
          repetition?: number;
          ease_factor?: number;
          next_review_at?: string | null;
          last_reviewed_at?: string | null;
          last_rating?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      daily_stats: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          new_cards: number;
          review_cards: number;
          completed: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          new_cards?: number;
          review_cards?: number;
          completed?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          new_cards?: number;
          review_cards?: number;
          completed?: number;
          created_at?: string;
        };
      };
      review_history: {
        Row: {
          id: string;
          user_id: string;
          grammar_id: string | null;
          grammar_key: string;
          rating: string;
          reviewed_at: string;
          interval: number;
          repetition: number;
          ease_factor: number;
          next_review_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          grammar_id?: string | null;
          grammar_key: string;
          rating: string;
          reviewed_at?: string;
          interval?: number;
          repetition?: number;
          ease_factor?: number;
          next_review_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          grammar_id?: string | null;
          grammar_key?: string;
          rating?: string;
          reviewed_at?: string;
          interval?: number;
          repetition?: number;
          ease_factor?: number;
          next_review_at?: string | null;
          created_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          user_id: string | null;
          type: "tip" | "pro_lifetime";
          provider: "wechat" | "alipay";
          channel: "native" | "h5" | "jsapi" | "mini_program";
          amount_cents: number;
          currency: string;
          status: "pending" | "paid" | "failed" | "closed" | "refunded";
          out_trade_no: string;
          provider_transaction_id: string | null;
          provider_prepay_id: string | null;
          qr_code_url: string | null;
          payer_openid: string | null;
          nickname: string | null;
          message: string | null;
          metadata: Json;
          paid_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          type: "tip" | "pro_lifetime";
          provider: "wechat" | "alipay";
          channel: "native" | "h5" | "jsapi" | "mini_program";
          amount_cents: number;
          currency?: string;
          status?: "pending" | "paid" | "failed" | "closed" | "refunded";
          out_trade_no: string;
          provider_transaction_id?: string | null;
          provider_prepay_id?: string | null;
          qr_code_url?: string | null;
          payer_openid?: string | null;
          nickname?: string | null;
          message?: string | null;
          metadata?: Json;
          paid_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          type?: "tip" | "pro_lifetime";
          provider?: "wechat" | "alipay";
          channel?: "native" | "h5" | "jsapi" | "mini_program";
          amount_cents?: number;
          currency?: string;
          status?: "pending" | "paid" | "failed" | "closed" | "refunded";
          out_trade_no?: string;
          provider_transaction_id?: string | null;
          provider_prepay_id?: string | null;
          qr_code_url?: string | null;
          payer_openid?: string | null;
          nickname?: string | null;
          message?: string | null;
          metadata?: Json;
          paid_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_entitlements: {
        Row: {
          id: string;
          user_id: string;
          plan: "free" | "pro";
          source_payment_id: string | null;
          lifetime: boolean;
          starts_at: string;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan: "free" | "pro";
          source_payment_id?: string | null;
          lifetime?: boolean;
          starts_at?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan?: "free" | "pro";
          source_payment_id?: string | null;
          lifetime?: boolean;
          starts_at?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payment_events: {
        Row: {
          id: string;
          payment_id: string | null;
          provider: "wechat" | "alipay";
          event_type: string;
          event_id: string | null;
          payload: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          payment_id?: string | null;
          provider: "wechat" | "alipay";
          event_type: string;
          event_id?: string | null;
          payload?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          payment_id?: string | null;
          provider?: "wechat" | "alipay";
          event_type?: string;
          event_id?: string | null;
          payload?: Json;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
