import type {
  GrammarEntry,
  UserStats,
  LevelProgress,
  ReviewRecord,
  FavoriteCollection,
} from "./types";

export const grammarEntries: GrammarEntry[] = [
  {
    id: "1",
    title: "～わけではない",
    slug: "wake-dewa-nai",
    jlptLevel: "N3",
    sourceRoute: "TRY",
    grammarType: "否定",
    tags: ["部分否定", "解释", "易混"],
    meaningCn: "并不是……；并非……",
    meaningEn: "it doesn't mean that; it's not that",
    structure: "普通形 + わけではない\nナ形語幹 + な + わけではない\n名詞 + な + わけではない",
    explanation:
      "用于对某个结论或推测进行部分否定。不否定事实本身，而是否定由此推出的结论。与「～ない」不同，语气更委婉、留有余地。",
    usageNote: "常与「からといって」「必ずしも」等搭配使用。口语中也说「～わけじゃない」。",
    exampleJp: "お金があれば幸せになれるというわけではない。",
    exampleCn: "并不是有钱就能幸福。",
    furigana: "おかねがあればしあわせになれるというわけではない。",
    similarGrammar: [
      {
        title: "～とは限らない",
        slug: "towa-kagiranai",
        difference: "「～とは限らない」表示不一定成立；「～わけではない」强调部分否定、不应简单得出结论。",
      },
      {
        title: "～ないことはない",
        slug: "nai-koto-wa-nai",
        difference: "「～ないことはない」是双重否定表示可能；「～わけではない」是部分否定。",
      },
    ],
    commonMistake: "不能用于否定事实本身。×「彼は学生なわけではない」（他是学生这个事实不能部分否定）",
    memoryTip: "「わけ」=理由、道理。所以「わけではない」=道理上不是这样 → 并不是那样。",
    quizQuestion: "お金が＿＿＿幸せになれるわけではない。",
    quizChoices: [
      { key: "A", text: "あれば" },
      { key: "B", text: "なくても" },
      { key: "C", text: "あるのに" },
      { key: "D", text: "あるから" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～ば～わけではない」表示'即使……也不一定……'。句意：并不是有钱就能幸福。",
    isFavorite: false,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 86400000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 2,
    masteryLevel: 35,
  },
  {
    id: "2",
    title: "～とは限らない",
    slug: "towa-kagiranai",
    jlptLevel: "N3",
    sourceRoute: "TRY",
    grammarType: "否定",
    tags: ["部分否定", "可能性"],
    meaningCn: "不一定……；未必……",
    meaningEn: "not necessarily; it doesn't always mean that",
    structure: "普通形 + とは限らない\n名詞 + だ + とは限らない",
    explanation:
      "表示某个结论或判断不一定成立，存在例外。暗示通常的认知可能不适用于当前情况。",
    usageNote: "常与「必ずしも」搭配使用。与「～わけではない」的区别在于更强调可能性而非部分否定。",
    exampleJp: "値段が高いものが必ずしも良いとは限らない。",
    exampleCn: "贵的东西不一定就是好的。",
    similarGrammar: [
      {
        title: "～わけではない",
        slug: "wake-dewa-nai",
        difference: "「～わけではない」是部分否定；「～とは限らない」强调存在例外的可能性。",
      },
    ],
    commonMistake: "注意与「～に限らない」（不限于）的区别，两者形式相近但意思不同。",
    memoryTip: "「限る」=限定。所以「限らない」=不能限定 → 不一定是那样。",
    quizQuestion: "値段が高いものが＿＿＿＿良いとは限らない。",
    quizChoices: [
      { key: "A", text: "必ずしも" },
      { key: "B", text: "まったく" },
      { key: "C", text: "すっかり" },
      { key: "D", text: "しっかり" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「必ずしも～とは限らない」是固定搭配，表示'不一定……'。",
    isFavorite: true,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 172800000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 1,
    masteryLevel: 20,
  },
  {
    id: "3",
    title: "～わけがない",
    slug: "wake-ga-nai",
    jlptLevel: "N3",
    sourceRoute: "一册合格",
    grammarType: "否定",
    tags: ["强烈否定", "不可能"],
    meaningCn: "不可能……；不会……",
    meaningEn: "there is no way that; impossible",
    structure: "普通形 + わけがない",
    explanation:
      "表示强烈的否定判断，基于客观理由断言某事不可能发生。语气比「～はずがない」更强。",
    usageNote: "口语中也说「～わけない」。与「～はずがない」相比，「わけがない」更强调基于道理的判断。",
    exampleJp: "こんなに難しい問題が簡単に解けるわけがない。",
    exampleCn: "这么难的问题不可能简单就能解开。",
    similarGrammar: [
      {
        title: "～はずがない",
        slug: "hazu-ga-nai",
        difference: "「はずがない」基于常识判断；「わけがない」基于道理和逻辑判断，语气更强。",
      },
    ],
    commonMistake: "不能与「～ないはずがない」等双重否定连用，会造成语义混乱。",
    memoryTip: "「わけ」=道理，「がない」=没有。所以字面意思是'没有道理'→不可能。",
    quizQuestion: "こんなに難しい問題が簡単に＿＿＿＿わけがない。",
    quizChoices: [
      { key: "A", text: "解ける" },
      { key: "B", text: "解けない" },
      { key: "C", text: "解いた" },
      { key: "D", text: "解こう" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～わけがない」前接动词辞书形。句意：不可能简单解开。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "4",
    title: "～ようにする",
    slug: "you-ni-suru",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "意志・勧誘",
    tags: ["努力", "习惯", "目标"],
    meaningCn: "努力做到……；设法……",
    meaningEn: "try to; make sure to; make an effort to",
    structure: "辞書形 + ようにする\nない形 + ようにする",
    explanation:
      "表示说话人有意识地努力做某事，或将某种行为变成习惯。不是单纯地'做'，而是带有'刻意去做到'的语感。",
    usageNote: "常用于表示决心或习惯养成。过去式「～ようにした」表示已经开始努力。",
    exampleJp: "健康のために、毎日30分歩くようにしています。",
    exampleCn: "为了健康，我坚持每天走30分钟。",
    similarGrammar: [
      {
        title: "～ことにする",
        slug: "koto-ni-suru",
        difference: "「ことにする」是做出决定；「ようにする」是努力坚持、养成习惯。",
      },
    ],
    commonMistake: "注意与「～ために」的区别。「ようにする」强调人的意志行为；「ために」表目的。",
    memoryTip: "「ように」=像那样、以那种状态。「する」=做。合起来：朝着那个状态去努力。",
    quizQuestion: "健康のために、毎日30分＿＿＿＿ようにしています。",
    quizChoices: [
      { key: "A", text: "歩く" },
      { key: "B", text: "歩いた" },
      { key: "C", text: "歩かない" },
      { key: "D", text: "歩け" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～ようにしている」表示坚持做某事，前接动词辞书形。",
    isFavorite: false,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 259200000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 3,
    masteryLevel: 60,
  },
  {
    id: "5",
    title: "～ことにする",
    slug: "koto-ni-suru",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "意志・勧誘",
    tags: ["决定", "选择"],
    meaningCn: "决定……；选择……",
    meaningEn: "decide to; choose to",
    structure: "辞書形 + ことにする\nない形 + ことにする",
    explanation:
      "表示说话人自己做出的决定，强调主观意志。与「～ようと思う」相比，「～ことにする」是已经做出决定。",
    usageNote: "过去式「～ことにした」表示已经决定。「～ことになっている」表示规则或安排。",
    exampleJp: "毎朝ジョギングをすることにしました。",
    exampleCn: "我决定每天早上慢跑。",
    similarGrammar: [
      {
        title: "～ようにする",
        slug: "you-ni-suru",
        difference: "「ことにする」是一次性决定，「ようにする」是持续性的努力和习惯养成。",
      },
    ],
    commonMistake: "不用来描述他人的决定。描述他人决定时用「～ことにしたそうだ」。",
    memoryTip: "「こと」=事情，「にする」=定为。合起来：把事情定为→决定。",
    quizQuestion: "毎朝ジョギングをする＿＿＿＿。",
    quizChoices: [
      { key: "A", text: "ことにした" },
      { key: "B", text: "ようにした" },
      { key: "C", text: "ものにした" },
      { key: "D", text: "はずにした" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～ことにした」表示已经做出的个人决定。句意：决定每天早上慢跑。",
    isFavorite: false,
    studyStatus: "已掌握",
    nextReviewAt: new Date(Date.now() + 604800000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 5,
    masteryLevel: 85,
  },
  {
    id: "6",
    title: "～ばかり",
    slug: "bakari",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "限定",
    tags: ["只", "光", "净是"],
    meaningCn: "光……；只……；净是……",
    meaningEn: "only; nothing but; always",
    structure: "名詞 + ばかり\n動詞て形 + ばかり",
    explanation:
      "表示某事物过多或行为过于频繁，带有说话人不满或批评的语气。也用于单纯表示数量多。",
    usageNote: "口语中常用于抱怨。也可以客观描述，如「今年は雨ばかりだ」。",
    exampleJp: "息子は毎日ゲームばかりしている。",
    exampleCn: "儿子每天光玩游戏。",
    similarGrammar: [
      {
        title: "～だけ",
        slug: "dake",
        difference: "「だけ」是客观限定；「ばかり」带有主观感情色彩（不满、批评）。",
      },
    ],
    commonMistake: "「ばかり」与「だけ」不能简单互换。「だけ」是中性的，「ばかり」常带负面色彩。",
    memoryTip: "想象「ばかり」发音像'霸道'→霸道地只有这个→净是。",
    quizQuestion: "息子は毎日ゲーム＿＿＿＿している。",
    quizChoices: [
      { key: "A", text: "ばかり" },
      { key: "B", text: "だけ" },
      { key: "C", text: "しか" },
      { key: "D", text: "ぐらい" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～てばかりいる」表示频繁重复某个行为，带有批评语气。句意：儿子一天到晚就知道打游戏。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "7",
    title: "～たばかり",
    slug: "ta-bakari",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "その他",
    tags: ["刚刚", "刚做完"],
    meaningCn: "刚刚……",
    meaningEn: "just; have just done",
    structure: "動詞た形 + ばかり",
    explanation:
      "表示某个动作刚刚完成不久。说话人主观上认为时间间隔很短。与「～たところ」相似，但不能与「～たばかり」后接过去式。",
    usageNote: "不能用于客观上很久以前但主观认为不久的情况。",
    exampleJp: "さっき昼ごはんを食べたばかりなのに、もうお腹がすいた。",
    exampleCn: "刚刚才吃过午饭，肚子却又饿了。",
    similarGrammar: [
      {
        title: "～たところ",
        slug: "ta-tokoro",
        difference: "「たばかり」偏主观感受（感觉刚做完），「たところ」偏客观（确实刚做完）。",
      },
    ],
    commonMistake: "「たばかり」后不接过去式。不能说「～たばかりだった」。",
    memoryTip: "「ばかり」+ 过去式 = 刚做完的状态。记住「たばかり」一起记。",
    quizQuestion: "さっき昼ごはんを＿＿＿＿ばかりなのに、もうお腹がすいた。",
    quizChoices: [
      { key: "A", text: "食べた" },
      { key: "B", text: "食べる" },
      { key: "C", text: "食べている" },
      { key: "D", text: "食べなかった" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～たばかり」必须接在动词た形之后。句意：明明刚吃完午饭却又饿了。",
    isFavorite: true,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 86400000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 1,
    masteryLevel: 25,
  },
  {
    id: "8",
    title: "～ために（目的）",
    slug: "tame-ni-mokuteki",
    jlptLevel: "N4",
    sourceRoute: "一册合格",
    grammarType: "目的",
    tags: ["目的", "为了"],
    meaningCn: "为了……",
    meaningEn: "for the purpose of; in order to",
    structure: "辞書形 + ために\n名詞 + の + ために",
    explanation:
      "表示为了实现某个目的而进行的行为。前项是意志动词，且前后主语必须一致。与表示原因的「～ために」要注意区分。",
    usageNote: "目的用法时前后主语必须一致。前后主语不同时用「～ように」。",
    exampleJp: "JLPTに合格するために、毎日勉強しています。",
    exampleCn: "为了通过JLPT，我每天都在学习。",
    similarGrammar: [
      {
        title: "～ように（目的）",
        slug: "you-ni-mokuteki",
        difference: "「ために」前接意志动词，「ように」前接非意志动词或可能态。",
      },
    ],
    commonMistake: "目的用法必须前后主语一致。不能说「私が使うために、彼が買った」。",
    memoryTip: "「ため」=为了(目的)。「に」=为某个方向。助你记住是'为了做某事'。",
    quizQuestion: "JLPTに合格する＿＿＿＿毎日勉強しています。",
    quizChoices: [
      { key: "A", text: "ように" },
      { key: "B", text: "ために" },
      { key: "C", text: "ことで" },
      { key: "D", text: "わけで" },
    ],
    quizAnswer: "B",
    quizExplanation:
      "「合格する」是意志动词，前后主语一致，用「ために」。句意：为通过JLPT每天学习。",
    isFavorite: false,
    studyStatus: "已掌握",
    nextReviewAt: new Date(Date.now() + 1209600000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 6,
    masteryLevel: 90,
  },
  {
    id: "9",
    title: "～ように（目的）",
    slug: "you-ni-mokuteki",
    jlptLevel: "N4",
    sourceRoute: "一册合格",
    grammarType: "目的",
    tags: ["目的", "状态目标"],
    meaningCn: "为了……（能达到某种状态）",
    meaningEn: "so that; in order to (reach a state)",
    structure: "辞書形（無意志動詞） + ように\nない形 + ように\n可能形 + ように",
    explanation:
      "表示为了实现某个状态或结果而进行的行为。前接非意志动词（可能态、自动词等），或前后主语不同时使用。",
    usageNote: "前后主语不同时必须用「ように」不能用「ために」。否定形式也用「ように」。",
    exampleJp: "日本語が上手に話せるように、毎日練習しています。",
    exampleCn: "为了能流利地说日语，我每天都在练习。",
    similarGrammar: [
      {
        title: "～ために（目的）",
        slug: "tame-ni-mokuteki",
        difference: "「ために」接意志动词（自己能控制的动作），「ように」接非意志动词（状态、结果）。",
      },
    ],
    commonMistake: "意志动词「勉強する」+「ように」❌。应该说「勉強するために」。",
    memoryTip: "「よう」=样子、状态。所以「ように」=为了达到那个状态→为了实现那个状态而做某事。",
    quizQuestion: "日本語が上手に話せる＿＿＿＿毎日練習しています。",
    quizChoices: [
      { key: "A", text: "ように" },
      { key: "B", text: "ために" },
      { key: "C", text: "ことに" },
      { key: "D", text: "もので" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「話せる」是可能态（非意志动词），用「ように」。句意：为能说好日语每天练习。",
    isFavorite: false,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 86400000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 2,
    masteryLevel: 40,
  },
  {
    id: "10",
    title: "～に違いない",
    slug: "ni-chigai-nai",
    jlptLevel: "N3",
    sourceRoute: "TRY",
    grammarType: "推量・様態",
    tags: ["肯定推测", "确信"],
    meaningCn: "一定……；肯定是……",
    meaningEn: "must be; no doubt; I'm sure that",
    structure: "普通形 + に違いない\n名詞 / ナ形語幹 + に違いない",
    explanation:
      "表示说话人基于某种依据的非常确信的推测。确信度比「～だろう」和「～はずだ」都高。",
    usageNote: "常用于书面语。口语中用「きっと～に違いない」。不能用于推测自己的事情。",
    exampleJp: "あの人はきっと日本人に違いない。",
    exampleCn: "那个人一定是日本人。",
    similarGrammar: [
      {
        title: "～はずだ",
        slug: "hazu-da",
        difference: "「はずだ」基于逻辑推理；「に違いない」基于直观和确信，语气更强烈。",
      },
      {
        title: "～かもしれない",
        slug: "kamo-shirenai",
        difference: "「かもしれない」可能性约50%；「に違いない」接近100%确信。",
      },
    ],
    commonMistake: "不能对自己将来的事情使用。不能说「私は来年合格するに違いない」。",
    memoryTip: "「違い」=不同、差别。「ない」=没有。所以「違いない」=没有差别→毫无疑问→一定是。",
    quizQuestion: "あの人は＿＿＿＿日本人に違いない。",
    quizChoices: [
      { key: "A", text: "きっと" },
      { key: "B", text: "たぶん" },
      { key: "C", text: "まるで" },
      { key: "D", text: "ちょうど" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「きっと～に違いない」常搭配使用，加强肯定推测语气。句意：那个人应该是日本人。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "11",
    title: "～らしい（推量）",
    slug: "rashii-suiron",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "推量・様態",
    tags: ["推测", "传闻判断"],
    meaningCn: "似乎……；好像……",
    meaningEn: "seems like; appears to be; I heard that",
    structure: "普通形 + らしい\n名詞 + らしい",
    explanation:
      "表示基于某种客观依据（传闻、迹象、信息）进行的推测判断。与「～ようだ」相似，但「らしい」更强调信息来源的客观性。",
    usageNote: "比「そうだ（传闻）」多了一层说话人的判断，比「ようだ」更客观。",
    exampleJp: "天気予報によると、明日は雨が降るらしい。",
    exampleCn: "据天气预报说，明天好像要下雨。",
    similarGrammar: [
      {
        title: "～ようだ",
        slug: "you-da",
        difference: "「ようだ」基于自己的直接感受；「らしい」基于听到的信息或客观迹象。",
      },
      {
        title: "～そうだ（传闻）",
        slug: "sou-da-denmon",
        difference: "「そうだ」是纯转述；「らしい」加入了说话人的判断。",
      },
    ],
    commonMistake: "不要与表示典型特征的「～らしい」（如「男らしい」）混淆。",
    memoryTip: "「らしい」听起来像'拉稀'？不！是'似乎'的意思。记住天气预报常说「～らしい」。",
    quizQuestion: "天気予報によると、明日は雨が＿＿＿＿らしい。",
    quizChoices: [
      { key: "A", text: "降る" },
      { key: "B", text: "降った" },
      { key: "C", text: "降らない" },
      { key: "D", text: "降っている" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～らしい」前接动词辞书形，表示推测。句意：据天气预报说明天会下雨。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "12",
    title: "～ようだ",
    slug: "you-da",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "推量・様態",
    tags: ["推测", "比喻", "举例"],
    meaningCn: "好像……；就像……",
    meaningEn: "seems like; looks like; as if",
    structure: "普通形 + ようだ\n名詞 + の + ようだ\nナ形語幹 + な + ようだ",
    explanation:
      "用法有三：①基于自己的五官感受进行的推测；②比喻（像……一样）；③举例。口语中用「～みたいだ」。",
    usageNote: "比「らしい」更主观，基于说话人自己的感觉。不是转述他人的话。",
    exampleJp: "彼女はまるで天使のように優しい。",
    exampleCn: "她就像天使一样温柔。",
    similarGrammar: [
      {
        title: "～らしい（推量）",
        slug: "rashii-suiron",
        difference: "「ようだ」基于直接感受；「らしい」基于间接信息。",
      },
    ],
    commonMistake: "比喻用法不能用「らしい」替换。不能说「天使らしい優しい」。",
    memoryTip: "「よう」=样子。所以「ようだ」=是那个样子→好像。比喻=像~的样子。",
    quizQuestion: "彼女はまるで天使の＿＿＿＿優しい。",
    quizChoices: [
      { key: "A", text: "ように" },
      { key: "B", text: "らしく" },
      { key: "C", text: "そうに" },
      { key: "D", text: "みたい" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～のように」用于比喻，表示'像……一样'。句意：她像天使一样温柔。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "13",
    title: "～そうだ（様態）",
    slug: "sou-da-youtai",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "推量・様態",
    tags: ["样态", "看起来"],
    meaningCn: "看起来……；似乎要……",
    meaningEn: "looks like; seems like; appears to",
    structure: "動詞ます形 + そうだ\nイ形語幹 + そうだ\nナ形語幹 + そうだ",
    explanation:
      "表示说话人通过视觉等感官直接观察后做出的样态判断。描述事物的外观或即将发生的状态。",
    usageNote: "「いい」→「よさそうだ」、「ない」→「なさそうだ」是不规则变形。不能用「きれいそうだ」要说「きれいだそうだ」（传闻）。",
    exampleJp: "このケーキはとてもおいしそうだ。",
    exampleCn: "这个蛋糕看起来很好吃。",
    similarGrammar: [
      {
        title: "～そうだ（伝聞）",
        slug: "sou-da-denmon",
        difference: "样态接ます形；传闻接普通形。样态是直接观察，传闻是转述。",
      },
    ],
    commonMistake: "不能直接修饰名词吗？可以说。如「おいしそうなケーキ」但注意「いい」→「よさそうな」。",
    memoryTip: "「そう」=那样。眼前看到就是「そうだ」=看起来那样。区分传闻时接续不同。",
    quizQuestion: "このケーキはとてもおいし＿＿＿＿。",
    quizChoices: [
      { key: "A", text: "そうだ" },
      { key: "B", text: "ようだ" },
      { key: "C", text: "らしい" },
      { key: "D", text: "みたいだ" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「おいしい」→语干「おいし」+「そうだ」=样态。句意：蛋糕看起来很好吃。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "14",
    title: "～ても",
    slug: "temo",
    jlptLevel: "N5",
    sourceRoute: "TRY",
    grammarType: "逆接・譲歩",
    tags: ["即使", "让步", "逆接"],
    meaningCn: "即使……也……",
    meaningEn: "even if; even though",
    structure: "動詞て形 + も\nイ形 → くて + も\nナ形 / 名詞 + でも",
    explanation:
      "表示逆接条件：即使前项条件成立，后项结果也不受影响。是日语中最基础的逆接表达之一。",
    usageNote: "口语中非常常用。与「～のに」的区别：「のに」表示意外或不满，「ても」是纯客观的让步。",
    exampleJp: "雨が降っても、試合は行われます。",
    exampleCn: "即使下雨，比赛也会进行。",
    similarGrammar: [
      {
        title: "～のに",
        slug: "noni",
        difference: "「ても」是纯让步条件；「のに」含意外或不满感情。",
      },
    ],
    commonMistake: "注意变形：イ形容词「いい」→「よくても」（不是「いくても」）。",
    memoryTip: "「て形」+「も」=即使。最简单也最常用的逆接。记住：ても＝即使。",
    quizQuestion: "雨が＿＿＿＿、試合は行われます。",
    quizChoices: [
      { key: "A", text: "降っても" },
      { key: "B", text: "降るのに" },
      { key: "C", text: "降って" },
      { key: "D", text: "降るから" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「降る」的て形「降って」+「も」=「降っても」。句意：即使下雨比赛也进行。",
    isFavorite: false,
    studyStatus: "已掌握",
    nextReviewAt: new Date(Date.now() + 604800000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 4,
    masteryLevel: 80,
  },
  {
    id: "15",
    title: "～のに",
    slug: "noni",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "逆接・譲歩",
    tags: ["逆接", "意外", "不满"],
    meaningCn: "明明……却……",
    meaningEn: "although; even though; despite",
    structure: "普通形 + のに\nナ形語幹 + な + のに\n名詞 + な + のに",
    explanation:
      "表示与预期相反的结果，常带有说话人的意外、不满、遗憾等感情色彩。比「～ても」更多主观情感。",
    usageNote: "口语中非常常用。后半句不能接命令、意志等表达。",
    exampleJp: "たくさん勉強したのに、試験に落ちてしまった。",
    exampleCn: "明明学了很多，考试却没通过。",
    similarGrammar: [
      {
        title: "～ても",
        slug: "temo",
        difference: "「ても」是纯让步；「のに」含主观意外或不满。",
      },
    ],
    commonMistake: "注意な形容词和名词要加「な」。如「静かなのに」不是「静かのに」。",
    memoryTip: "「のに」=明明~却。带着抱怨的语气记住它。",
    quizQuestion: "たくさん勉強した＿＿＿＿、試験に落ちてしまった。",
    quizChoices: [
      { key: "A", text: "のに" },
      { key: "B", text: "ても" },
      { key: "C", text: "から" },
      { key: "D", text: "ので" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「のに」表示转折，带有遗憾语气。句意：明明学了很多却落榜了。",
    isFavorite: true,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 86400000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 2,
    masteryLevel: 45,
  },
  {
    id: "16",
    title: "～ながら",
    slug: "nagara",
    jlptLevel: "N5",
    sourceRoute: "TRY",
    grammarType: "並列",
    tags: ["同时进行", "一边一边"],
    meaningCn: "一边……一边……",
    meaningEn: "while; as; simultaneously",
    structure: "動詞ます形 + ながら",
    explanation:
      "表示同一主体同时进行两个动作。主次关系：后项为主要动作，前项为伴随动作。前后主语必须相同。",
    usageNote: "两个动作必须同一主体。持续动作用「～ながら」。瞬间动作用「～ていて」。",
    exampleJp: "音楽を聞きながら勉強するのが好きです。",
    exampleCn: "我喜欢一边听音乐一边学习。",
    similarGrammar: [
      {
        title: "～つつ",
        slug: "tsutsu",
        difference: "「ながら」是口语常用；「つつ」是书面语，正式文体中使用。",
      },
    ],
    commonMistake: "前后主语必须相同。不能说「母が料理をしながら、私は勉強した」。",
    memoryTip: "「ながら」=while。最简单的用法！记住「聞きながら」=听的同时。",
    quizQuestion: "音楽を＿＿＿＿勉強するのが好きです。",
    quizChoices: [
      { key: "A", text: "聞きながら" },
      { key: "B", text: "聞くながら" },
      { key: "C", text: "聞いたながら" },
      { key: "D", text: "聞いてながら" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「ながら」必须接在动词ます形之后。句意：喜欢边听音乐边学习。",
    isFavorite: false,
    studyStatus: "已掌握",
    nextReviewAt: new Date(Date.now() + 1209600000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 5,
    masteryLevel: 85,
  },
  {
    id: "17",
    title: "～に比べて",
    slug: "ni-kurabete",
    jlptLevel: "N3",
    sourceRoute: "一册合格",
    grammarType: "比較",
    tags: ["比较", "对比"],
    meaningCn: "与……相比",
    meaningEn: "compared to; in comparison with",
    structure: "名詞 + に比べて",
    explanation:
      "用于将两个事物进行对比。可以对比大小、数量、程度等各方面的差异。",
    usageNote: "正式场合也用「～と比べて」。口语中可省略后面的动词。",
    exampleJp: "去年に比べて、今年の冬は暖かいですね。",
    exampleCn: "和去年相比，今年冬天真暖和啊。",
    similarGrammar: [
      {
        title: "～に対して",
        slug: "ni-taishite",
        difference: "「に比べて」是单纯比较；「に対して」还含有'针对、回应'的意思。",
      },
    ],
    commonMistake: "比较对象必须是同一范畴。不能说「東京は大阪に比べて人口が多い」。应改为「東京の人口は大阪に比べて多い」。",
    memoryTip: "「比べる」=比较。所以「に比べて」=与~相比。直观好记。",
    quizQuestion: "去年に＿＿＿＿、今年の冬は暖かいですね。",
    quizChoices: [
      { key: "A", text: "比べて" },
      { key: "B", text: "対して" },
      { key: "C", text: "ついて" },
      { key: "D", text: "関して" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～に比べて」表示比较。句意：与去年相比今年冬天暖和。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "18",
    title: "～について",
    slug: "ni-tsuite",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "その他",
    tags: ["关于", "就……而言"],
    meaningCn: "关于……；就……",
    meaningEn: "about; concerning; regarding",
    structure: "名詞 + について",
    explanation:
      "用于提出话题，表示'关于某个主题'。是最常用的表示话题的语法之一。",
    usageNote: "比「～に関して」更口语化、更常用。「～については」表示限定话题。",
    exampleJp: "日本の文化について調べています。",
    exampleCn: "我正在调查关于日本文化。",
    similarGrammar: [
      {
        title: "～に関して",
        slug: "ni-kanshite",
        difference: "「について」是口语常用；「に関して」更正式，多用于书面语。",
      },
      {
        title: "～に対して",
        slug: "ni-taishite",
        difference: "「について」是关于内容；「に対して」是对对象的态度或反应。",
      },
    ],
    commonMistake: "不能用于表达对某个对象的态度。不能说「先生について失礼だ」。",
    memoryTip: "「つく」=附着。所以「について」=附着在那个话题上→关于那个话题。",
    quizQuestion: "日本の文化に＿＿＿＿調べています。",
    quizChoices: [
      { key: "A", text: "ついて" },
      { key: "B", text: "関して" },
      { key: "C", text: "対して" },
      { key: "D", text: "とって" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～について」表示'关于……'。句意：在调查日本文化。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "19",
    title: "～に関して",
    slug: "ni-kanshite",
    jlptLevel: "N3",
    sourceRoute: "一册合格",
    grammarType: "その他",
    tags: ["关于", "正式"],
    meaningCn: "关于……（正式）",
    meaningEn: "regarding; concerning; with regard to",
    structure: "名詞 + に関して",
    explanation:
      "与「～について」类似但更正式，多用于书面语、商务、学术发表等正式场合。",
    usageNote: "正式场合优先用「に関して」。日常对话中用「について」更自然。",
    exampleJp: "この問題に関して、ご意見をお聞かせください。",
    exampleCn: "关于这个问题，请告诉我您的意见。",
    similarGrammar: [
      {
        title: "～について",
        slug: "ni-tsuite",
        difference: "「について」是通用表达；「に関して」更正式，用于商务或学术场景。",
      },
    ],
    commonMistake: "日常会话中过度使用会显得生硬。朋友聊天用「について」更自然。",
    memoryTip: "「関する」=相关。所以「に関して」=与~相关→关于。正式场合用。",
    quizQuestion: "この問題に＿＿＿＿ご意見をお聞かせください。",
    quizChoices: [
      { key: "A", text: "関して" },
      { key: "B", text: "ついて" },
      { key: "C", text: "対して" },
      { key: "D", text: "とって" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～に関して」表示正式地'关于……'。句意：关于此问题请说意见。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "20",
    title: "～として",
    slug: "toshite",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "その他",
    tags: ["身份", "立场", "资格"],
    meaningCn: "作为……；以……身份/立场",
    meaningEn: "as; in the capacity of",
    structure: "名詞 + として",
    explanation:
      "表示立场、身份、资格。明确指出以什么样的身份或资格来做某事。",
    usageNote: "可以用于表示从某个角度来看。如「私としては～」='就我个人而言……'。",
    exampleJp: "私は留学生として日本に来ました。",
    exampleCn: "我作为留学生来到了日本。",
    similarGrammar: [
      {
        title: "～にとって",
        slug: "ni-totte",
        difference: "「として」表示身份立场；「にとって」表示'对……来说'（从某人角度看）。",
      },
    ],
    commonMistake: "不要与「～にとって」混淆。「先生として」=作为老师；「先生にとって」=对老师来说。",
    memoryTip: "「と」+「して」=作为。简单！「留学生として」=作为留学生。",
    quizQuestion: "私は留学生＿＿＿＿日本に来ました。",
    quizChoices: [
      { key: "A", text: "として" },
      { key: "B", text: "にとって" },
      { key: "C", text: "について" },
      { key: "D", text: "に対して" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～として」表示身份立场。句意：作为留学生来到日本。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
  {
    id: "21",
    title: "～はずだ",
    slug: "hazu-da",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "推量・様態",
    tags: ["应该", "按理说"],
    meaningCn: "应该……；按道理……",
    meaningEn: "should; ought to; must be",
    structure: "普通形 + はずだ\nナ形語幹 + な + はずだ\n名詞 + の + はずだ",
    explanation:
      "表示基于逻辑推理的判断，说话人认为某件事按理应该成立。确信度较高。",
    usageNote: "否定形式「～はずがない」表示'不可能'。不能用于确定事实。",
    exampleJp: "彼はもうすぐ来るはずです。",
    exampleCn: "他应该马上就到了。",
    similarGrammar: [
      {
        title: "～に違いない",
        slug: "ni-chigai-nai",
        difference: "「はずだ」基于逻辑；「に違いない」更主观确信，语气更强。",
      },
    ],
    commonMistake: "已知事实不能用「はず」。不能说「今日は月曜日のはずだ」（已知是周一）。",
    memoryTip: "「はず」=应该。英语的should。记住「来るはず」=应该会来。",
    quizQuestion: "彼はもうすぐ＿＿＿＿はずです。",
    quizChoices: [
      { key: "A", text: "来る" },
      { key: "B", text: "来た" },
      { key: "C", text: "来ている" },
      { key: "D", text: "来ない" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「～はずだ」前接动词辞书形。句意：他应该马上到。",
    isFavorite: false,
    studyStatus: "学习中",
    nextReviewAt: new Date(Date.now() + 86400000).toISOString(),
    lastReviewedAt: new Date().toISOString(),
    reviewCount: 1,
    masteryLevel: 30,
  },
  {
    id: "22",
    title: "～ために（原因）",
    slug: "tame-ni-genin",
    jlptLevel: "N4",
    sourceRoute: "TRY",
    grammarType: "原因・理由",
    tags: ["原因", "因为"],
    meaningCn: "因为……；由于……",
    meaningEn: "because of; due to; on account of",
    structure: "普通形 + ために\n名詞 + の + ために",
    explanation:
      "表示原因，后项是消极或不好的结果。与表示目的的「～ために」要注意区分。",
    usageNote: "后项通常是不好的结果。主语不要求一致（与目的用法不同）。",
    exampleJp: "台風のために、電車が止まってしまった。",
    exampleCn: "因为台风，电车停了。",
    similarGrammar: [
      {
        title: "～せいで",
        slug: "sei-de",
        difference: "「せいで」含责怪语气；「ために」相对中立。",
      },
    ],
    commonMistake: "注意与目的用法的区别。原因用法前后主语可不一致，目的用法必须一致。",
    memoryTip: "「ため」=因为、由于。不好的结果后面来。记住「台風のために」。",
    quizQuestion: "台風の＿＿＿＿電車が止まってしまった。",
    quizChoices: [
      { key: "A", text: "ために" },
      { key: "B", text: "ように" },
      { key: "C", text: "ことに" },
      { key: "D", text: "わけに" },
    ],
    quizAnswer: "A",
    quizExplanation:
      "「名詞 + の + ために」表示原因。句意：因台风电车停了。",
    isFavorite: false,
    studyStatus: "未学习",
    nextReviewAt: null,
    lastReviewedAt: null,
    reviewCount: 0,
    masteryLevel: 0,
  },
];

// Helper to get entries by level
export function getEntriesByLevel(level: string): GrammarEntry[] {
  return grammarEntries.filter((e) => e.jlptLevel === level);
}

// Helper to get level stats
export function getLevelProgress(): LevelProgress[] {
  const levels = ["N5", "N4", "N3", "N2", "N1"] as const;
  return levels.map((level) => {
    const entries = getEntriesByLevel(level);
    return {
      level,
      total: entries.length,
      learned: entries.filter((e) => e.studyStatus === "学习中" || e.studyStatus === "已掌握")
        .length,
      mastered: entries.filter((e) => e.studyStatus === "已掌握").length,
    };
  });
}

// User stats
export const userStats: UserStats = {
  todayNewCards: 5,
  todayReviewCards: 15,
  todayCompleted: 8,
  todayTotal: 20,
  totalLearned: 12,
  totalMastered: 5,
  totalFavorites: 3,
  streakDays: 5,
};

// Review records
export const reviewRecords: ReviewRecord[] = grammarEntries
  .filter((e) => e.studyStatus === "学习中")
  .map((e) => ({
    grammarId: e.id,
    title: e.title,
    level: e.jlptLevel,
    lastRating: e.reviewCount > 0 ? (e.masteryLevel > 50 ? "记住了" : "有点模糊") : "未复习",
    nextReviewDate: e.nextReviewAt
      ? new Date(e.nextReviewAt).toLocaleDateString("zh-CN")
      : "未安排",
    isFavorite: e.isFavorite,
  }));

// Favorite collections
export const favoriteCollections: FavoriteCollection[] = [
  { id: "1", name: "默认收藏", count: 3 },
  { id: "2", name: "易错语法", count: 0 },
  { id: "3", name: "考前复习", count: 0 },
  { id: "4", name: "N2 重点", count: 0 },
  { id: "5", name: "敬语专项", count: 0 },
];

export const favorites = grammarEntries.filter((e) => e.isFavorite);
